//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Kv6Receiver.bison {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg", IsNullable=false)]
    public partial class VV_TM_PUSH {
        
        private string subscriberIDField;
        
        private string versionField;
        
        private DossierNameType dossierNameField;
        
        private System.DateTime timestampField;
        
        private KV6posinfoType[] kV6posinfoField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DossierNameType DossierName {
            get {
                return this.dossierNameField;
            }
            set {
                this.dossierNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KV6posinfo")]
        public KV6posinfoType[] KV6posinfo {
            get {
                return this.kV6posinfoField;
            }
            set {
                this.kV6posinfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public enum DossierNameType {
        
        /// <remarks/>
        KV6posinfo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class KV6posinfoType {
        
        private object[] itemsField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ARRIVAL", typeof(ARRIVALType))]
        [System.Xml.Serialization.XmlElementAttribute("DELAY", typeof(DELAYType))]
        [System.Xml.Serialization.XmlElementAttribute("DEPARTURE", typeof(DEPARTUREType))]
        [System.Xml.Serialization.XmlElementAttribute("END", typeof(ENDType))]
        [System.Xml.Serialization.XmlElementAttribute("INIT", typeof(INITType))]
        [System.Xml.Serialization.XmlElementAttribute("OFFROUTE", typeof(OFFROUTEType))]
        [System.Xml.Serialization.XmlElementAttribute("ONPATH", typeof(ONPATHType))]
        [System.Xml.Serialization.XmlElementAttribute("ONROUTE", typeof(ONROUTEType))]
        [System.Xml.Serialization.XmlElementAttribute("ONSTOP", typeof(ONSTOPType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class ARRIVALType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private int vehiclenumberField;
        
        private int punctualityField;
        
        private delimiter delimiterField;
        
        private int rdxField;
        
        private bool rdxFieldSpecified;
        
        private int rdyField;
        
        private bool rdyFieldSpecified;
        
        private delimiter[] delimiter1Field;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int punctuality {
            get {
                return this.punctualityField;
            }
            set {
                this.punctualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/core", Order=11)]
        public delimiter delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-x", Order=12)]
        public int rdx {
            get {
                return this.rdxField;
            }
            set {
                this.rdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rdxSpecified {
            get {
                return this.rdxFieldSpecified;
            }
            set {
                this.rdxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-y", Order=13)]
        public int rdy {
            get {
                return this.rdyField;
            }
            set {
                this.rdyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rdySpecified {
            get {
                return this.rdyFieldSpecified;
            }
            set {
                this.rdyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core", Order=14)]
        public delimiter[] delimiter1 {
            get {
                return this.delimiter1Field;
            }
            set {
                this.delimiter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=15)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public enum sourceType {
        
        /// <remarks/>
        VEHICLE,
        
        /// <remarks/>
        SERVER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/core", IsNullable=false)]
    public partial class delimiter {
        
        private string sinceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string since {
            get {
                return this.sinceField;
            }
            set {
                this.sinceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class ENDType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private int vehiclenumberField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class OFFROUTEType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private int vehiclenumberField;
        
        private int rdxField;
        
        private int rdyField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-x")]
        public int rdx {
            get {
                return this.rdxField;
            }
            set {
                this.rdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-y")]
        public int rdy {
            get {
                return this.rdyField;
            }
            set {
                this.rdyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class ONPATHType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private int vehiclenumberField;
        
        private int distancesincelastuserstopField;
        
        private bool distancesincelastuserstopFieldSpecified;
        
        private int rdxField;
        
        private int rdyField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        public int distancesincelastuserstop {
            get {
                return this.distancesincelastuserstopField;
            }
            set {
                this.distancesincelastuserstopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distancesincelastuserstopSpecified {
            get {
                return this.distancesincelastuserstopFieldSpecified;
            }
            set {
                this.distancesincelastuserstopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-x")]
        public int rdx {
            get {
                return this.rdxField;
            }
            set {
                this.rdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-y")]
        public int rdy {
            get {
                return this.rdyField;
            }
            set {
                this.rdyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class ONROUTEType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private int vehiclenumberField;
        
        private int punctualityField;
        
        private int distancesincelastuserstopField;
        
        private bool distancesincelastuserstopFieldSpecified;
        
        private int rdxField;
        
        private int rdyField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        public int punctuality {
            get {
                return this.punctualityField;
            }
            set {
                this.punctualityField = value;
            }
        }
        
        /// <remarks/>
        public int distancesincelastuserstop {
            get {
                return this.distancesincelastuserstopField;
            }
            set {
                this.distancesincelastuserstopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distancesincelastuserstopSpecified {
            get {
                return this.distancesincelastuserstopFieldSpecified;
            }
            set {
                this.distancesincelastuserstopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-x")]
        public int rdx {
            get {
                return this.rdxField;
            }
            set {
                this.rdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-y")]
        public int rdy {
            get {
                return this.rdyField;
            }
            set {
                this.rdyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class DEPARTUREType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private int vehiclenumberField;
        
        private int punctualityField;
        
        private delimiter delimiterField;
        
        private int rdxField;
        
        private bool rdxFieldSpecified;
        
        private int rdyField;
        
        private bool rdyFieldSpecified;
        
        private delimiter[] delimiter1Field;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int punctuality {
            get {
                return this.punctualityField;
            }
            set {
                this.punctualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/core", Order=11)]
        public delimiter delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-x", Order=12)]
        public int rdx {
            get {
                return this.rdxField;
            }
            set {
                this.rdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rdxSpecified {
            get {
                return this.rdxFieldSpecified;
            }
            set {
                this.rdxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-y", Order=13)]
        public int rdy {
            get {
                return this.rdyField;
            }
            set {
                this.rdyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rdySpecified {
            get {
                return this.rdyFieldSpecified;
            }
            set {
                this.rdyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core", Order=14)]
        public delimiter[] delimiter1 {
            get {
                return this.delimiter1Field;
            }
            set {
                this.delimiter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=15)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class ONSTOPType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private int vehiclenumberField;
        
        private int punctualityField;
        
        private delimiter delimiterField;
        
        private int rdxField;
        
        private bool rdxFieldSpecified;
        
        private int rdyField;
        
        private bool rdyFieldSpecified;
        
        private delimiter[] delimiter1Field;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int punctuality {
            get {
                return this.punctualityField;
            }
            set {
                this.punctualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/core", Order=11)]
        public delimiter delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-x", Order=12)]
        public int rdx {
            get {
                return this.rdxField;
            }
            set {
                this.rdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rdxSpecified {
            get {
                return this.rdxFieldSpecified;
            }
            set {
                this.rdxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rd-y", Order=13)]
        public int rdy {
            get {
                return this.rdyField;
            }
            set {
                this.rdyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rdySpecified {
            get {
                return this.rdyFieldSpecified;
            }
            set {
                this.rdyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core", Order=14)]
        public delimiter[] delimiter1 {
            get {
                return this.delimiter1Field;
            }
            set {
                this.delimiter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=15)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class INITType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private int vehiclenumberField;
        
        private int blockcodeField;
        
        private wheelchairaccessibleType wheelchairaccessibleField;
        
        private int numberofcoachesField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public int vehiclenumber {
            get {
                return this.vehiclenumberField;
            }
            set {
                this.vehiclenumberField = value;
            }
        }
        
        /// <remarks/>
        public int blockcode {
            get {
                return this.blockcodeField;
            }
            set {
                this.blockcodeField = value;
            }
        }
        
        /// <remarks/>
        public wheelchairaccessibleType wheelchairaccessible {
            get {
                return this.wheelchairaccessibleField;
            }
            set {
                this.wheelchairaccessibleField = value;
            }
        }
        
        /// <remarks/>
        public int numberofcoaches {
            get {
                return this.numberofcoachesField;
            }
            set {
                this.numberofcoachesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public enum wheelchairaccessibleType {
        
        /// <remarks/>
        ACCESSIBLE,
        
        /// <remarks/>
        NOTACCESSIBLE,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public partial class DELAYType {
        
        private string dataownercodeField;
        
        private string lineplanningnumberField;
        
        private System.DateTime operatingdayField;
        
        private int journeynumberField;
        
        private int reinforcementnumberField;
        
        private System.DateTime timestampField;
        
        private sourceType sourceField;
        
        private int punctualityField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        public string lineplanningnumber {
            get {
                return this.lineplanningnumberField;
            }
            set {
                this.lineplanningnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime operatingday {
            get {
                return this.operatingdayField;
            }
            set {
                this.operatingdayField = value;
            }
        }
        
        /// <remarks/>
        public int journeynumber {
            get {
                return this.journeynumberField;
            }
            set {
                this.journeynumberField = value;
            }
        }
        
        /// <remarks/>
        public int reinforcementnumber {
            get {
                return this.reinforcementnumberField;
            }
            set {
                this.reinforcementnumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public sourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public int punctuality {
            get {
                return this.punctualityField;
            }
            set {
                this.punctualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg", IsNullable=false)]
    public partial class VV_TM_REQ {
        
        private string subscriberIDField;
        
        private string versionField;
        
        private DossierNameType dossierNameField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DossierNameType DossierName {
            get {
                return this.dossierNameField;
            }
            set {
                this.dossierNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg", IsNullable=false)]
    public partial class VV_TM_RES {
        
        private string subscriberIDField;
        
        private string versionField;
        
        private DossierNameType dossierNameField;
        
        private System.DateTime timestampField;
        
        private ResponseCodeType responseCodeField;
        
        private string responseErrorField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DossierNameType DossierName {
            get {
                return this.dossierNameField;
            }
            set {
                this.dossierNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public ResponseCodeType ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseError {
            get {
                return this.responseErrorField;
            }
            set {
                this.responseErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/msg")]
    public enum ResponseCodeType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        PE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv6/core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv6/core", IsNullable=false)]
    public partial class end {
    }
}
